# TODO 添加必要的配置信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webtest?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  # 文件上传相关配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 512KB

server:
  port: 80
# 配置上传图片保存路径
image:
  path: E:/Code/IDEAWeb/BBSboot/src/main/resources/static/webResources/
